theme: jekyll-theme-slate
title: Technology stack for mobile game development
name: goopymoon
avatar: https://avatars2.githubusercontent.com/u/11221412?s=400&u=26b549e89e2530c7a8e60eeaa3f0bec495f7e81d&v=4
